name: team_manager_application
description: "A Flutter Application designed to aid in managing University Club Teams"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  fluttertoast: ^8.2.6
<<<<<<< HEAD
  firebase_database: ^11.0.3
  youtube_player_flutter: ^9.0.1
=======
  http: ^1.2.1
  firebase_database: ^11.0.2
  
>>>>>>> 4ebeb33281a26d5fd094e83f8a54d2a38ab91922

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Whitney
      fonts:
        - asset: lib/assets/fonts/whitneybold.otf
        - asset: lib/assets/fonts/whitneymedium.otf
        - asset: lib/assets/fonts/whitneylight.otf

